development: 
  trusted_frontend_ip: 
  - 127.0.0.1
  - 111.111.111.111
  - 222.222.222.222
  jbrowse_data:
    /srv/jbrowse

test:
  trusted_frontend_ip: 
  - 111.111.111.111
  - 127.0.0.1
  jbrowse_data:
    /data/jbrowse

production:
  trusted_frontend_ip: 
  - 222.222.222.222
  jbrowse_data:
    /data/jbrowse
